(defun tic-tac-toe ()
  (print 'tic-tac-toe)
  (terpri))

(defun draw-board ()
  (terpri)(terpri)
  (print '"     |     |     ")
  (print '"  0  |  1  |  2  ")
  (print '"_____|_____|_____")
  (print '"     |     |     ")
  (print '"  3  |  4  |  5  ")
  (print '"_____|_____|_____")
  (print '"     |     |     ")
  (print '"  6  |  7  |  8  ")
  (print '"     |     |     ")(terpri)(terpri))
